parameters:
  - name: serviceName
    type: string

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: ${{ parameters.serviceName }}
  displayName: 'Compile time'

- script: $(parameters.serviceName)
  displayName: 'Run time'
