pool:
  vmImage: windows-latest

trigger: none

pr: none

name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)


steps:
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'ServiceConnection'
      KeyVaultName: 'azdbkvdev202308'
      SecretsFilter: '*'
      RunAsPreJob: false      

  - task: CmdLine@2
    inputs:
      script: |
        echo $(Password) > secret.txt
        echo $(Password2) > secret.txt
        echo $(Password3) > secret.txt
        cat secret.txt

  - task: CopyFiles@2
    inputs:
      Contents: secret.txt
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
