parameters:
  - name: serviceName
    type: string
    displayName: Service Name
    
  - name: Plan
    type: string
    values:
      - AppServicePlan
      - Consumption
    displayName: App Service Plan

variables:
- name: myconditionalvariable
  ${{ if eq( parameters.Plan, 'AppServicePlan' ) }}: 
    value: apps
  ${{ if eq( parameters.Plan, 'Consumption' ) }}: 
    value: cons
    
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: echo ${{ parameters.serviceName }}
  displayName: 'Compile time'

- bash: echo "##vso[task.setvariable variable=serviceName]bose"
  displayName: Set new variable value

- script: echo $(serviceName)
  displayName: 'Run time' 

- script: |
    echo ${{ parameters.Plan }}
    echo $(myconditionalvariable)
