parameters:
  - name: serviceName
    type: string
    displayName: Service Name
    
  - name: planType
    type: string
    values:
      - AppServicePlan
      - Consumption
    displayName: App Service Plan

variables:
- name: planName
  ${{ if eq( parameters.planType, 'AppServicePlan' ) }}: 
    value: 'ASP-devaufnrg-apps'
  ${{ if eq( parameters.planType, 'Consumption' ) }}: 
    value: 'ASP-devaufnrg-b633'    

pool:
  vmImage: windows-latest

trigger: none

pr: none

name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

stages:
  - stage: Build
    jobs:       
    - template: 'jobs/build-job.yml'
  
  - stage: Development-AU
    dependsOn: Build
    condition: succeeded('Build')
    displayName: 'Staging AU'
    jobs:  
    - template: 'jobs/function/function-deploy-job.yml'
      parameters:
        environmentName: DEV
        siteName: ${{ parameters.serviceName }}
        hostingPlanName: ${{ variables.planName }}

  - stage: Development-US
    dependsOn: Development-AU
    condition: succeeded('Development-AU')
    displayName: 'Staging US'
    jobs:  
    - template: 'jobs/function/function-deploy-job.yml'
      parameters:
        environmentName: DEV
        siteName: ${{ parameters.serviceName }}
        hostingPlanName: ${{ variables.planName }}

  - stage: Production-AU
    dependsOn: Development-US
    condition: succeeded('Development-US')
    displayName: 'Prod AU'
    jobs:  
    - template: 'jobs/function/function-deploy-job.yml'
      parameters:
        environmentName: PROD
        siteName: ${{ parameters.serviceName }}
        hostingPlanName: ${{ variables.planName }}           