parameters:
  - name: serviceName
    type: string
    displayName: Service Name
    
  - name: planType
    type: string
    values:
      - AppServicePlan
      - Consumption
    displayName: App Service Plan

variables:
- name: planName
  ${{ if eq( parameters.planType, 'AppServicePlan' ) }}: 
    value: 'ASP-devaufnrg-apps'
  ${{ if eq( parameters.planType, 'Consumption' ) }}: 
    value: 'ASP-devaufnrg-b633'    

pool:
  vmImage: windows-latest

trigger: none

pr: none

name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

stages:
  - stage: Build
    jobs:       
    - template: 'jobs/build-job.yml'
  
  - stage: Development_AU
    dependsOn: Build
    condition: succeeded('Build')
    displayName: 'Staging AU'
    jobs: 
    - job: 
      steps: 
        - script: |
           echo ${{ variables.AUFunctionName }}    
    variables:
    - template: 'variables/pipeline-variables.DEV.yml'
      parameters:
        serviceName: ${{ parameters.serviceName }}          

  - stage: Development_US
    dependsOn: Build
    condition: succeeded('Build')
    displayName: 'Staging US'
    jobs:  
    - template: 'jobs/function/function-deploy-job.yml'
      parameters:
        environmentName: DEV
        siteName: ${{ variables.USFunctionName  }}
        hostingPlanName: ${{ variables.planName }}
    variables:
    - template: 'variables/pipeline-variables.DEV.yml'
      parameters:
        serviceName: ${{ parameters.serviceName }}

  - stage: Production_AU
    dependsOn: Development_AU
    condition: succeeded('Development_AU')
    displayName: 'Prod AU'
    jobs:  
    - template: 'jobs/function/function-deploy-job.yml'
      parameters:
        environmentName: PROD
        siteName: ${{ variables.AUFunctionName }}
        hostingPlanName: ${{ variables.planName }}

  - stage: Production_US
    dependsOn: Development_US
    condition: succeeded('Development_US')
    displayName: 'Prod US'
    jobs:  
    - template: 'jobs/function/function-deploy-job.yml'
      parameters:
        environmentName: PROD
        siteName: ${{ variables.USFunctionName }}
        hostingPlanName: ${{ variables.planName }}        