parameters:
- name: environmentName
  type: string

- name: siteName
  type: string  

- name: hostingPlanName
  type: string  

- name: planType
  type: string

jobs:
  - deployment: AzureFunction
    displayName: Deploy Azure Function
    environment: '${{ parameters.environmentName }}'
    variables:
    - template: '../../variables/pipeline-variables.${{ parameters.environmentName }}.yml'
      parameters:
        serviceName: siteName
    strategy: 
      runOnce:
        deploy:
          steps:

          - script: echo "Determine plan"
          - ${{ if eq(parameters.planType, 'AppServicePlan') }}:
            - bash: |
                echo "##vso[task.setvariable variable=myVar;]$(Test1)"
          - ${{ if eq(parameters.planType, 'Consumption') }}:
            - bash: |
                echo "##vso[task.setvariable variable=myVar;]$(Test2)"
          - script: |
              echo $(myVar) 

 