parameters:
- name: environmentName
  type: string

- name: siteName
  type: string  

- name: hostingPlanName
  type: string  

jobs:
  - deployment: AzureFunction
    displayName: Deploy Azure Function
    environment: '${{ parameters.environmentName }}'
    variables:
    - template: '../../variables/pipeline-variables.${{ parameters.environmentName }}.yml'
      parameters:
        serviceName: siteName
    strategy: 
      runOnce:
        deploy:
          steps:

          - script: 'Determine plan'
          - ${{ if eq(parameters.environmentName, 'DEV') }}:
            - script: echo "Hello World"

 