jobs: 
- job: BuildJob
  displayName: Build
  variables:
    buildConfiguration: 'Release'

  steps:
    - task: CopyFiles@2
      displayName: 'Build Artifacts | Copy | Bicep'
      inputs:
        SourceFolder: 'bicep'
        contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)/bicep'

    - task: PublishBuildArtifacts@1
      displayName: 'Build Artifacts | Publish'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: drop
      condition: succeededOrFailed()